import { Geist, Geist_Mono } from "next/font/google";
import "../globals.css";
import Navbar from "../componets/Navbar";
import AuthNavbar from "../componets/AuthNavbar";

export const metadata = {
  title: "Auth Routes",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
      >
       <AuthNavbar />
        {children}
      </body>
    </html>
  );
}

